#python3 /root/workspace/OpenNMT-py/translate.py -gpu 4 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.01 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.01 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.01
python3 /root/workspace/OpenNMT-py/translate.py -gpu 4 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.02 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.02 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.02
python3 /root/workspace/OpenNMT-py/translate.py -gpu 4 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.03 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.03 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.03
python3 /root/workspace/OpenNMT-py/translate.py -gpu 4 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.04 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.04 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.04
python3 /root/workspace/OpenNMT-py/translate.py -gpu 4 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.05 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.05 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.05


python3 /root/workspace/OpenNMT-py/translate.py -gpu 5 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.06 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.06 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.06
python3 /root/workspace/OpenNMT-py/translate.py -gpu 5 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.07 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.07 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.07
python3 /root/workspace/OpenNMT-py/translate.py -gpu 5 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.08 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.08 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.08
python3 /root/workspace/OpenNMT-py/translate.py -gpu 5 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.09 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.09 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.09
python3 /root/workspace/OpenNMT-py/translate.py -gpu 5 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.10 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.10 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.10

python3 /root/workspace/OpenNMT-py/translate.py -gpu 6 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.11 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.11 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.11
python3 /root/workspace/OpenNMT-py/translate.py -gpu 6 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.12 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.12 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.12
python3 /root/workspace/OpenNMT-py/translate.py -gpu 6 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.13 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.13 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.13
python3 /root/workspace/OpenNMT-py/translate.py -gpu 6 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.14 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.14 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.14
python3 /root/workspace/OpenNMT-py/translate.py -gpu 6 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.15 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.15 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.15

python3 /root/workspace/OpenNMT-py/translate.py -gpu 7 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.16 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.16 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.16
python3 /root/workspace/OpenNMT-py/translate.py -gpu 7 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.17 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.17 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.17
python3 /root/workspace/OpenNMT-py/translate.py -gpu 7 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.18 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.18 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.18
python3 /root/workspace/OpenNMT-py/translate.py -gpu 7 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.19 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.19 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.19
python3 /root/workspace/OpenNMT-py/translate.py -gpu 7 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.20 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.20 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.20

python3 /root/workspace/OpenNMT-py/translate.py -gpu 0 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.21 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.21 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.21
python3 /root/workspace/OpenNMT-py/translate.py -gpu 0 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/distill/my_corpus.en.atok-v4-.train.under100.22 -tgt /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.22 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.train.under100.mycorpus_model_v4_enzh_step_160000.pt.22


# validation and test
python3 /root/workspace/OpenNMT-py/translate.py -gpu 0 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/my_corpus.en.atok-v4-.test -tgt /root/workspace/translate_data/my_corpus.zh.atok-v4-.test -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.test.mycorpus_model_v4_enzh_step_160000.pt
python3 /root/workspace/OpenNMT-py/translate.py -gpu 0 -model mycorpus_model_v4_step_160000.pt -src /root/workspace/translate_data/my_corpus.en.atok-v4-.val.under100 -tgt /root/workspace/translate_data/my_corpus.zh.atok-v4-.val.under100 -replace_unk -verbose -output /root/workspace/translate_data/distill/my_corpus.zh.atok-v4-.val.under100.mycorpus_model_v4_enzh_step_160000.pt
